window.COURSE = {
  meta: {
    title: { th: 'HIS AI Product Workshop', en: 'HIS AI Product Workshop' },
    subtitle: {
      th: 'เรียนรู้การทำ Product ด้วย AI Agent สำหรับ PM, BA และ Product Design โดยไม่ต้องเริ่มจากการเขียนโค้ด',
      en: 'AI-assisted product development for PM, BA, and Product Design — without starting from coding.'
    },
    starterUrl: 'https://github.com/somprasongd/his-ai-opd-checkin-starter',
    sourceUrl: 'https://github.com/somprasongd/his-ai-product-workshop',
    pagesUrl: 'https://somprasongd.github.io/his-ai-product-workshop/'
  },
  groups: [
    { id:'start', th:'เตรียมพร้อม', en:'Get ready' },
    { id:'day1', th:'Day 1 · จาก Requirement สู่ AI Workspace', en:'Day 1 · Requirement to AI Workspace' },
    { id:'day2', th:'Day 2 · จาก Requirement สู่ Component', en:'Day 2 · Requirement to Components' },
    { id:'day3', th:'Day 3 · Integration, Debug & Delivery', en:'Day 3 · Integration, Debug & Delivery' },
    { id:'capstone', th:'Capstone', en:'Capstone' }
  ],
  lessons: [
    {
      id:'prerequisites', group:'start', no:'00', duration:'45 min', kind:'setup',
      title:{th:'Prerequisites & Environment Setup',en:'Prerequisites & Environment Setup'},
      intro:{th:'เตรียมเครื่องมือให้พร้อมก่อนเริ่ม เพื่อให้เวลาเรียนใช้ไปกับการเข้าใจ workflow ไม่ใช่การแก้ปัญหา installation',en:'Prepare the environment first so class time is spent understanding the workflow, not fighting installation issues.'},
      outcomes:{th:['รู้ว่าเครื่องมือแต่ละตัวใช้ทำอะไร','ตรวจสอบว่า Git, Node.js, Editor และ AI Agent พร้อมใช้งาน','Clone Starter Repository และรัน Next.js/Storybook ได้','เข้าใจกฎข้อมูลสำหรับ training: ใช้ mock/synthetic data เท่านั้น'],en:['Know what each tool is for','Verify Git, Node.js, editor, and AI agent setup','Clone the starter repository and run Next.js/Storybook','Understand the training data rule: mock/synthetic data only']},
      blocks:[
        {type:'callout',tone:'warning',title:{th:'เป้าหมายของคอร์สนี้',en:'Course boundary'},text:{th:'คอร์สนี้ไม่สอน Backend, Database หรือ REST API implementation เราจะจำลอง Data/API เพื่อโฟกัสที่ Product thinking, UI states, Git workflow และการกำกับ AI Agent',en:'This course does not teach backend, database, or REST API implementation. Data/API behavior is mocked so we can focus on product thinking, UI states, Git workflow, and supervising an AI agent.'}},
        {type:'list',title:{th:'ติดตั้งก่อนเรียน',en:'Install before class'},items:{th:['Git เวอร์ชันปัจจุบัน','Node.js 20.9+ (ข้อกำหนดขั้นต่ำของ Next.js 16)','VS Code หรือ editor ที่ทีมใช้','Chrome หรือ Edge สำหรับ DevTools','เลือก AI Agent อย่างน้อย 1 ตัว: Codex CLI หรือ Claude Code','GitHub account สำหรับ starter repo และสิทธิ์ GitLab self-hosted ของบริษัทสำหรับ workflow จริง'],en:['Current Git','Node.js 20.9+ (minimum for Next.js 16)','VS Code or your team editor','Chrome or Edge for DevTools','At least one AI agent: Codex CLI or Claude Code','A GitHub account for the starter repo and access to the company self-hosted GitLab for real workflow practice']}},
        {type:'code',label:'Verify',code:`git --version\nnode --version\nnpm --version`},
        {type:'code',label:'Codex CLI · macOS/Linux',code:`curl -fsSL https://chatgpt.com/codex/install.sh | sh\ncodex`},
        {type:'practice',title:{th:'ลงมือทำ: เปิด Starter Repository',en:'Practice: open the Starter Repository'},steps:{th:['Fork หรือ Clone starter repository','รัน npm install','รัน npm run dev แล้วเปิด http://localhost:3000','เปิดอีก terminal แล้วรัน npm run storybook และเปิด http://localhost:6006'],en:['Fork or clone the starter repository','Run npm install','Run npm run dev and open http://localhost:3000','Open another terminal, run npm run storybook, then open http://localhost:6006']},expected:{th:'เห็นหน้า Training Starter และ Storybook เปิดได้โดยไม่มี error สำคัญ',en:'The Training Starter page and Storybook both open without significant errors.'},code:`git clone https://github.com/somprasongd/his-ai-opd-checkin-starter.git\ncd his-ai-opd-checkin-starter\nnpm install\nnpm run dev\n# new terminal\nnpm run storybook`}
      ],
      quiz:{q:{th:'ถ้า Storybook เปิดได้แต่ Next.js เปิดไม่ได้ สิ่งแรกที่ควรทำคืออะไร?',en:'If Storybook opens but Next.js does not, what should you do first?'},options:{th:['ติดตั้ง Database','อ่าน error ใน terminal ของ Next.js','ลบ repository แล้ว clone ใหม่'],en:['Install a database','Read the error in the Next.js terminal','Delete the repository and clone again']},answer:1,why:{th:'เริ่มจาก evidence ก่อนเสมอ: อ่าน error ที่ process ซึ่งล้มเหลว แล้วค่อยให้ Agent ช่วยวิเคราะห์',en:'Start with evidence: read the error from the failing process, then ask the agent to analyze it.'}},
      wrap:{th:['Environment พร้อมก่อนเข้าเนื้อหา','รู้จุดแบ่งระหว่าง training mock กับ production system','รู้คำสั่งเปิด Next.js และ Storybook'],en:['Environment ready before the course','Know the boundary between training mocks and production systems','Know how to start Next.js and Storybook']}
    },
    {
      id:'mental-model', group:'day1', no:'01', duration:'45 min',
      title:{th:'AI Product Development Mental Model',en:'AI Product Development Mental Model'},
      intro:{th:'เริ่มจากภาพใหญ่ก่อน: Requirement หนึ่งเรื่องเดินทางอย่างไรจาก Issue ไปเป็น UI ที่ review และ merge ได้',en:'Start with the big picture: how one requirement travels from an issue to a reviewable, mergeable UI.'},
      outcomes:{th:['เข้าใจ Repository, Page, Component, State, Branch และ Merge Request ในระดับใช้งาน','เห็นบทบาทของ Human กับ AI Agent แยกจากกัน','รู้ว่า “AI ทำเสร็จ” ยังไม่เท่ากับ “งานเสร็จ”'],en:['Understand Repository, Page, Component, State, Branch, and Merge Request at a practical level','Separate human responsibility from AI-agent responsibility','Understand that “AI finished” is not the same as “work finished”']},
      blocks:[
        {type:'diagram',title:{th:'เส้นทางของงาน',en:'The work journey'},diagram:`flowchart LR\nR[Requirement] --> I[GitLab Issue]\nI --> W[Branch + Worktree]\nW --> A[AI Agent]\nA --> C[Component + Story]\nC --> P[Next.js Page]\nP --> V[Human Verify]\nV --> D[git diff + checks]\nD --> M[Merge Request]`},
        {type:'two',title:{th:'ใครรับผิดชอบอะไร',en:'Who owns what'},left:{title:{th:'Human',en:'Human'},items:{th:['นิยาม outcome และ acceptance criteria','ตรวจ scope, state, edge case และ usability','อนุมัติ plan ก่อนเปลี่ยนไฟล์สำคัญ','ตรวจ Storybook, running app และ git diff'],en:['Define outcomes and acceptance criteria','Review scope, states, edge cases, and usability','Approve plans before significant changes','Review Storybook, running app, and git diff']}},right:{title:{th:'AI Agent',en:'AI Agent'},items:{th:['สำรวจ repository','เสนอ plan','สร้าง/แก้ component และ story','รัน command, test และช่วยวิเคราะห์ error'],en:['Explore the repository','Propose a plan','Create/edit components and stories','Run commands/tests and help analyze errors']}}},
        {type:'callout',title:{th:'กฎหลักตลอดคอร์ส',en:'Core rule for the whole course'},text:{th:'อย่าให้ Agent กระโดดจาก Requirement ไป Implement ทันที ให้ผ่าน Explore → Plan → Human Review → Implement → Verify',en:'Do not let the agent jump straight from Requirement to implementation. Use Explore → Plan → Human Review → Implement → Verify.'}},
        {type:'practice',title:{th:'ลงมือทำ: สำรวจ repo โดยยังไม่แก้ไฟล์',en:'Practice: explore without changing files'},steps:{th:['เปิด starter repo ใน editor','หา README.md, AGENTS.md, src/app, src/features, src/mocks และ .storybook','อธิบายด้วยภาษาของตัวเองว่าแต่ละส่วนมีหน้าที่อะไร'],en:['Open the starter repo in your editor','Find README.md, AGENTS.md, src/app, src/features, src/mocks, and .storybook','Explain in your own words what each area is for']},expected:{th:'ผู้เรียนสามารถชี้ตำแหน่งของ page, feature code, mock และ agent instruction ได้ แม้ยังอ่านโค้ดไม่คล่อง',en:'You can point to the page, feature code, mocks, and agent instructions even if you are not comfortable reading code yet.'}}
      ],
      quiz:{q:{th:'จุดใดควรเกิดก่อน Agent เริ่ม Implement?',en:'What should happen before the agent begins implementation?'},options:{th:['Human review แผน','Merge Request','Production deploy'],en:['Human review of the plan','Merge Request','Production deploy']},answer:0,why:{th:'Plan review เป็นจุดควบคุม scope ที่สำคัญที่สุดสำหรับผู้ใช้ AI ที่ไม่ใช่ developer',en:'Plan review is one of the strongest scope-control points for non-developer AI users.'}},
      wrap:{th:['เข้าใจ end-to-end workflow','แยก Human judgment กับ Agent execution','รู้ว่าการ verify เป็นส่วนหนึ่งของ Definition of Done'],en:['Understand the end-to-end workflow','Separate human judgment from agent execution','Know that verification is part of the Definition of Done']}
    },
    {
      id:'git-basics', group:'day1', no:'02', duration:'60 min',
      title:{th:'Git Fundamentals สำหรับคนที่ไม่ได้เป็น Developer',en:'Git Fundamentals for Non-Developers'},
      intro:{th:'เรียน Git เท่าที่ต้องใช้เพื่อควบคุมงานของ AI: รู้ว่าเราอยู่ตรงไหน เปลี่ยนอะไร และจะส่งงานอย่างปลอดภัยอย่างไร',en:'Learn only the Git needed to supervise AI work: where you are, what changed, and how to deliver safely.'},
      outcomes:{th:['เข้าใจ Local/Remote, main, Branch, Commit, Push/Pull และ MR','ใช้ git status และ git diff เป็นนิสัย','รู้คำสั่งที่ควรหลีกเลี่ยงในช่วงเริ่มต้น'],en:['Understand Local/Remote, main, Branch, Commit, Push/Pull, and MR','Build the habit of git status and git diff','Know which commands to avoid early on']},
      blocks:[
        {type:'diagram',title:{th:'Git ในภาพเดียว',en:'Git in one picture'},diagram:`flowchart LR\nL[Local files] -->|git add + commit| B[Feature branch]\nB -->|git push| R[Remote GitHub/GitLab]\nR -->|Merge Request| M[main]\nM -->|git pull| L`},
        {type:'code',label:'Daily commands',code:`git status\ngit branch\ngit pull\ngit diff\ngit log --oneline --decorate -10`},
        {type:'two',title:{th:'ใช้บ่อย vs ยังไม่ต้องใช้',en:'Use now vs avoid for now'},left:{title:{th:'ใช้บ่อย',en:'Use often'},items:{th:['git status','git diff','git switch -c','git add / commit / push'],en:['git status','git diff','git switch -c','git add / commit / push']}},right:{title:{th:'ยังไม่ต้องใช้',en:'Avoid for now'},items:{th:['git reset --hard','git push --force','interactive rebase','คำสั่งที่ Agent ขอรันแต่ผู้เรียนอธิบายไม่ได้'],en:['git reset --hard','git push --force','interactive rebase','Any command the agent asks to run that you cannot explain']}}},
        {type:'practice',title:{th:'ลงมือทำ: Branch แรก',en:'Practice: your first branch'},steps:{th:['เช็กว่าอยู่ main และ working tree สะอาด','สร้าง branch feature/us001-patient-search','แก้ README เล็กน้อย','ใช้ git diff ดูการเปลี่ยนแปลง แล้ว restore กลับโดยไม่ commit'],en:['Confirm you are on main with a clean working tree','Create branch feature/us001-patient-search','Make a small README edit','Use git diff to inspect it, then restore without committing']},expected:{th:'สามารถสร้าง branch, เห็น diff และย้อนการแก้ไฟล์ที่ยังไม่ commit ได้',en:'You can create a branch, inspect a diff, and undo an uncommitted file edit.'},code:`git status\ngit switch -c feature/us001-patient-search\ngit diff\ngit restore README.md`}
      ],
      quiz:{q:{th:'คำสั่งไหนตอบคำถาม “AI เปลี่ยนอะไรไปบ้าง?” ได้ตรงที่สุด?',en:'Which command best answers “What did the AI change?”'},options:{th:['git diff','git clone','git branch -d'],en:['git diff','git clone','git branch -d']},answer:0,why:{th:'git diff คือหน้าต่างหลักในการตรวจการเปลี่ยนแปลงก่อน commit',en:'git diff is the primary window for reviewing changes before committing.'}},
      wrap:{th:['Git คือระบบควบคุมการเปลี่ยนแปลง ไม่ใช่เรื่องเฉพาะ Developer','status ก่อนทำ และ diff หลังทำ','main ไม่ใช่พื้นที่ทดลอง'],en:['Git is change control, not just a developer tool','status before work, diff after work','main is not a playground']}
    },
    {
      id:'worktree', group:'day1', no:'03', duration:'60 min',
      title:{th:'Git Worktree & Parallel AI',en:'Git Worktree & Parallel AI'},
      intro:{th:'แยก workspace ต่อ task เพื่อให้หลาย Agent หรือหลายงานทำพร้อมกันโดยไม่สลับ branch และไม่เอาไฟล์มาปนกัน',en:'Separate workspaces per task so multiple agents or tasks can run in parallel without branch switching or mixed file changes.'},
      outcomes:{th:['เข้าใจ 1 Issue = 1 Branch = 1 Worktree = 1 Agent Session','สร้าง/ดู/ลบ worktree ได้','รู้เรื่อง port conflict และ dependency ต่อ worktree','รู้ว่า parallel เหมาะเมื่อ task แยกกันจริง'],en:['Understand 1 Issue = 1 Branch = 1 Worktree = 1 Agent Session','Create/list/remove worktrees','Understand port conflicts and per-worktree dependencies','Use parallel work only when tasks are truly independent']},
      blocks:[
        {type:'diagram',title:{th:'หนึ่ง Repo หลาย Workspace',en:'One repo, multiple workspaces'},diagram:`flowchart TB\nR[(Repository)] --> M[main worktree]\nR --> W1[wt-us001\nfeature/us001]\nR --> W2[wt-us002\nfeature/us002]\nW1 --> A1[Agent A]\nW2 --> A2[Agent B]`},
        {type:'code',label:'Worktree essentials',code:`git worktree list\n\ngit worktree add ../wt-us001-patient-checkin \\\n  -b feature/us001-patient-checkin main\n\ncd ../wt-us001-patient-checkin\ngit status`},
        {type:'callout',tone:'warning',title:{th:'สิ่งที่มักเจอ',en:'Common friction'},text:{th:'แต่ละ worktree มีไฟล์ working copy ของตัวเอง จึงอาจต้อง npm install และถ้ารันหลาย Next.js/Storybook พร้อมกันต้องใช้คนละ port เช่น 3001/6001 และ 3002/6002',en:'Each worktree has its own working files, so you may need npm install. Multiple Next.js/Storybook processes also need different ports, e.g. 3001/6001 and 3002/6002.'}},
        {type:'practice',title:{th:'ลงมือทำ: สร้าง workspace ของ US-001',en:'Practice: create a workspace for US-001'},steps:{th:['กลับไป main worktree และ pull ล่าสุด','สร้าง worktree wt-us001-patient-checkin','เปิด editor ใหม่ที่ worktree นี้','รัน git worktree list และ git status เพื่อยืนยัน context'],en:['Return to the main worktree and pull latest','Create wt-us001-patient-checkin','Open a new editor window at that worktree','Run git worktree list and git status to confirm context']},expected:{th:'เห็น worktree อย่างน้อย 2 รายการ และ US-001 อยู่บน feature branch ของตัวเอง',en:'You see at least two worktrees, and US-001 is on its own feature branch.'}}
      ],
      quiz:{q:{th:'กฎไหนลดความสับสนได้ดีที่สุด?',en:'Which rule best reduces confusion?'},options:{th:['ทุก Agent ใช้ folder เดียว','1 task = 1 branch = 1 worktree','เปลี่ยน main โดยตรงเพื่อเร็วขึ้น'],en:['All agents use the same folder','1 task = 1 branch = 1 worktree','Edit main directly to move faster']},answer:1,why:{th:'การแยก task/branch/workspace ทำให้ขอบเขตการเปลี่ยนแปลงและ context ของ Agent ชัดเจน',en:'Separating task/branch/workspace keeps change boundaries and agent context clear.'}},
      wrap:{th:['Worktree คือ workspace ของ branch','Parallel ไม่ได้แปลว่าต้องเปิด Agent เยอะที่สุด','ตรวจ context ก่อนให้ Agent ทำงานเสมอ'],en:['A worktree is a workspace for a branch','Parallel does not mean “run as many agents as possible”','Confirm context before the agent starts']}
    },
    {
      id:'agent-plan', group:'day1', no:'04', duration:'75 min',
      title:{th:'AI Agent: Explore → Plan → Human Review',en:'AI Agent: Explore → Plan → Human Review'},
      intro:{th:'ฝึกสั่ง Agent ให้สำรวจระบบและอธิบายแผนก่อนแตะไฟล์ เพื่อให้คนที่ไม่เขียนโค้ดสามารถควบคุม scope ได้',en:'Train the agent to inspect and explain before touching files, giving non-coders a strong scope-control point.'},
      outcomes:{th:['เขียน prompt ที่มี context, constraints และ expected output','ให้ Agent อ่าน AGENTS.md ก่อนทำ','review plan ได้ด้วยคำถามด้าน scope/state/files/tests','รู้ว่า CLAUDE.md ใช้ reference ไปที่ AGENTS.md เพื่อลดกฎซ้ำ'],en:['Write prompts with context, constraints, and expected output','Make the agent read AGENTS.md first','Review plans using scope/state/files/tests questions','Use CLAUDE.md as a reference to AGENTS.md to avoid duplicated rules']},
      blocks:[
        {type:'code',label:'Explore prompt',code:`Read AGENTS.md and docs/requirements/US-001-opd-checkin.md.\n\nDo not modify any files yet.\n\n1. Inspect the project structure.\n2. Identify the smallest components needed.\n3. List required UI states and edge cases.\n4. Identify existing files that should be reused.\n5. List files you expect to create or change.\n6. Explain how you will verify the result.\n\nReturn a concise implementation plan for human review.`},
        {type:'list',title:{th:'คำถามที่ Human ใช้ review Plan',en:'Human plan-review questions'},items:{th:['เข้าใจ Requirement ถูกหรือยัง?','ขาด Loading / Empty / Error / Validation / Success หรือไม่?','ไฟล์ที่จะเปลี่ยนอยู่ใน scope หรือไม่?','กำลังสร้าง abstraction เกินจำเป็นหรือไม่?','Verification plan มี Storybook + running app + lint/test/build หรือไม่?'],en:['Does the plan understand the requirement correctly?','Are Loading / Empty / Error / Validation / Success states covered?','Are proposed files within scope?','Is the agent creating unnecessary abstraction?','Does verification include Storybook + running app + lint/test/build?']}},
        {type:'code',label:'Implement prompt after approval',code:`Implement the approved plan.\n\nConstraints:\n- Keep changes scoped to US-001.\n- Use mock/synthetic data only.\n- Pair reusable product components with Storybook stories.\n- Do not add a backend, database, auth system, or a new UI library.\n- Do not commit or push.\n\nWhen finished, run the relevant checks and summarize every changed file.`},
        {type:'practice',title:{th:'ลงมือทำ: ให้ Agent เสนอแผน US-001',en:'Practice: ask the agent to plan US-001'},steps:{th:['เปิด Agent ใน worktree US-001','ส่ง Explore Prompt','เปรียบเทียบ plan กับ acceptance criteria','ขอให้ Agent แก้ plan ถ้ายังขาด state หรือเปลี่ยนไฟล์กว้างเกินไป'],en:['Open the agent in the US-001 worktree','Send the Explore Prompt','Compare the plan with acceptance criteria','Ask the agent to revise the plan if states are missing or file scope is too broad']},expected:{th:'ได้ plan ที่ระบุ component, state, file scope และ verification โดยยังไม่มีไฟล์ถูกแก้',en:'You get a plan listing components, states, file scope, and verification, with no files changed yet.'}}
      ],
      quiz:{q:{th:'Prompt ที่ดีสำหรับเริ่มงานควรขาดอะไรไม่ได้?',en:'What must a good task-start prompt include?'},options:{th:['คำว่า “สวยๆ”','Context + constraints + expected output','ชื่อ model ที่ยาวที่สุด'],en:['The phrase “make it pretty”','Context + constraints + expected output','The longest model name']},answer:1,why:{th:'สามส่วนนี้ทำให้ Agent รู้ว่าต้องทำอะไร ห้ามทำอะไร และต้องรายงานอะไรกลับมา',en:'Those three elements tell the agent what to do, what not to do, and what to return.'}},
      wrap:{th:['AGENTS.md คือกติกาหลัก','Explore ก่อน Implement','Human review plan ก่อนอนุญาตให้แก้ไฟล์'],en:['AGENTS.md is the primary rulebook','Explore before implement','Human reviews the plan before file changes']}
    },
    {
      id:'next-literacy', group:'day2', no:'05', duration:'60 min',
      title:{th:'อ่าน Next.js Project โดยไม่ต้องเขียน React',en:'Read a Next.js Project Without Writing React'},
      intro:{th:'เรียนแผนที่ของ project เพื่อรู้ว่า Agent กำลังแตะส่วนไหน ไม่ได้เรียน React syntax แบบ Developer course',en:'Learn the project map so you know what the agent is touching — not React syntax as in a developer course.'},
      outcomes:{th:['หา page, feature, component, mock และ configuration ได้','อ่าน JSX/TSX ระดับ component + props ได้','รู้จัก package.json และ npm scripts','รู้ว่า route /opd/check-in มาจากโครงสร้าง app อย่างไร'],en:['Find pages, features, components, mocks, and configuration','Read JSX/TSX at component + props level','Understand package.json and npm scripts','Know how /opd/check-in maps to the app directory']},
      blocks:[
        {type:'code',label:'Project map',code:`src/\n├── app/\n│   └── opd/\n│       └── check-in/\n│           └── page.tsx\n├── features/\n│   └── opd-checkin/\n├── components/\n├── mocks/\n└── services/\n.storybook/\npackage.json\nAGENTS.md`},
        {type:'two',title:{th:'อ่าน TSX แบบ Product Person',en:'Read TSX like a product person'},left:{title:{th:'สิ่งที่เห็น',en:'What you see'},items:{th:['<PatientCard /> = เรียก Component','patient={patient} = ส่งข้อมูลเข้าไป','selected={true} = ส่ง state/option','onSelect={...} = มี interaction callback'],en:['<PatientCard /> = use a component','patient={patient} = pass data in','selected={true} = pass a state/option','onSelect={...} = interaction callback']}},right:{title:{th:'สิ่งที่ยังไม่ต้องเรียนลึก',en:'Not yet'},items:{th:['React lifecycle','Generic types','Server Component internals','State management libraries'],en:['React lifecycle','Generic types','Server Component internals','State management libraries']}}},
        {type:'code',label:'Example',code:`<PatientCard\n  patient={patient}\n  selected={selectedPatientId === patient.id}\n  onSelect={() => selectPatient(patient.id)}\n/>`},
        {type:'practice',title:{th:'ลงมือทำ: หา route และ script',en:'Practice: find the route and scripts'},steps:{th:['เปิด src/app/opd/check-in/page.tsx','เปิด package.json แล้วหา dev, storybook, lint, test และ build','ถาม Agent ให้ชี้ว่า component ใหม่สำหรับ feature ควรอยู่ที่ไหน โดยยังไม่แก้ไฟล์'],en:['Open src/app/opd/check-in/page.tsx','Open package.json and find dev, storybook, lint, test, and build scripts','Ask the agent where new feature components should live, without editing files']},expected:{th:'สามารถอธิบายว่า route, page และ feature folder เชื่อมกันอย่างไร และรู้คำสั่งที่ใช้รัน/ตรวจงาน',en:'You can explain how route, page, and feature folders connect and know the commands used to run/check work.'}}
      ],
      quiz:{q:{th:'เป้าหมายของบทนี้คืออะไร?',en:'What is the goal of this lesson?'},options:{th:['เขียน React Hook จากความจำ','รู้แผนที่ project และอ่าน component usage ได้','ออกแบบ Database schema'],en:['Write React Hooks from memory','Know the project map and read component usage','Design a database schema']},answer:1,why:{th:'เราต้องการ technical literacy เพื่อกำกับ Agent ไม่ใช่เปลี่ยน PM/BA/Designer ให้เป็น Developer ภายในหนึ่งคอร์ส',en:'We want technical literacy to supervise the agent, not turn PM/BA/Designers into developers in one course.'}},
      wrap:{th:['อ่าน structure ก่อนอ่าน syntax','รู้ตำแหน่ง page/component/mock','package.json คือจุดดูคำสั่งหลักของ project'],en:['Read structure before syntax','Know where pages/components/mocks live','package.json is the place to discover project commands']}
    },
    {
      id:'component-state', group:'day2', no:'06', duration:'75 min',
      title:{th:'Component Thinking & UI State',en:'Component Thinking & UI State'},
      intro:{th:'เปลี่ยน Requirement ที่เป็นข้อความให้เป็นหน่วย UI ที่เล็กพอสำหรับ Agent ทำงานและ Human review ได้',en:'Turn a textual requirement into UI units small enough for the agent to build and humans to review.'},
      outcomes:{th:['แตก Page → Component → State → Interaction','ระบุ meaningful states โดยไม่สร้าง story เกินจำเป็น','เชื่อมบทบาท PM/BA/Design ผ่าน artifact เดียวกัน','มอง edge case ก่อน Agent implement'],en:['Decompose Page → Component → State → Interaction','Define meaningful states without story inflation','Connect PM/BA/Design through one shared artifact','Surface edge cases before implementation']},
      blocks:[
        {type:'diagram',title:{th:'จาก Page ลงสู่สิ่งที่ทดสอบได้',en:'From page to testable pieces'},diagram:`flowchart TD\nP[OPD Check-in Page] --> S[PatientSearch]\nP --> R[PatientResults]\nP --> F[CheckInForm]\nP --> C[Confirmation]\nP --> X[Success]\nS --> S1[Default]\nS --> S2[Loading]\nS --> S3[Empty]\nS --> S4[WithResults]\nS --> S5[Error]`},
        {type:'two',title:{th:'มุมมองของแต่ละ Role',en:'Role lenses'},left:{title:{th:'PM + BA',en:'PM + BA'},items:{th:['Scope และ flow','Business rules','Validation','Acceptance criteria','Edge cases'],en:['Scope and flow','Business rules','Validation','Acceptance criteria','Edge cases']}},right:{title:{th:'Product Design',en:'Product Design'},items:{th:['Visual hierarchy','Component boundaries','Loading/empty/error states','Interaction','Responsive behavior'],en:['Visual hierarchy','Component boundaries','Loading/empty/error states','Interaction','Responsive behavior']}}},
        {type:'list',title:{th:'US-001 ที่เราจะสร้างต่อเนื่อง',en:'Our continuous US-001 example'},items:{th:['ค้นหาผู้ป่วยด้วย HN หรือชื่อ','ระหว่างค้นหาแสดง Loading','ไม่พบข้อมูลแสดง Empty','ผิดพลาดแสดง Error','เลือกผู้ป่วยและดูรายละเอียด','เลือก Clinic','Chief Complaint เป็น optional','Preview → Confirm → Success'],en:['Search patients by HN or name','Show Loading during search','Show Empty when no results','Show Error on failure','Select a patient and view details','Choose a Clinic','Chief Complaint is optional','Preview → Confirm → Success']}},
        {type:'practice',title:{th:'ลงมือทำ: State inventory',en:'Practice: state inventory'},steps:{th:['เขียน component ที่คิดว่าจำเป็นก่อนถาม Agent','สำหรับแต่ละ component เขียน states ที่มีผลต่อผู้ใช้','ให้ Agent critique ว่าขาด state/edge case หรือแตก component มากเกินไปหรือไม่','ปรับให้เหลือชุดที่ Human review ได้ง่าย'],en:['Write the components you think are needed before asking the agent','List user-visible states for each component','Ask the agent to critique missing states/edge cases or over-componentization','Refine to a set humans can review easily']},expected:{th:'ได้ component/state map ที่ครอบคลุม Default, Loading, Empty, Error, Data, Validation และ Success เท่าที่เกี่ยวข้อง',en:'A component/state map covering Default, Loading, Empty, Error, Data, Validation, and Success where relevant.'}}
      ],
      quiz:{q:{th:'Story “Default, DefaultWithPadding, DefaultWide, Default2” เป็นสัญญาณอะไร?',en:'What does a story set like “Default, DefaultWithPadding, DefaultWide, Default2” suggest?'},options:{th:['State design ชัดมาก','อาจกำลังสร้าง story ตาม implementation detail มากกว่า meaningful user state','ต้องเพิ่มอีก 10 stories'],en:['Excellent state design','Stories may be tracking implementation details rather than meaningful user states','Add ten more stories']},answer:1,why:{th:'Story ควรสื่อ state/behavior ที่มีความหมายต่อ requirement และ review',en:'Stories should communicate states/behaviors meaningful to requirements and review.'}},
      wrap:{th:['Component Thinking สำคัญกว่า React syntax สำหรับกลุ่มนี้','State inventory ช่วยจับ requirement ที่ตกหล่น','ไม่ใช่ทุก div ต้องเป็น component หรือ story'],en:['Component thinking matters more than React syntax for this audience','State inventory catches missing requirements','Not every div needs a component or story']}
    },
    {
      id:'storybook', group:'day2', no:'07', duration:'75 min',
      title:{th:'Component + Storybook ต้องเกิดคู่กัน',en:'Build Components and Stories Together'},
      intro:{th:'ใช้ Storybook เป็น review surface ของ Product Component ก่อนประกอบเข้า Page โดยให้ AI เขียน code แต่ Human นิยาม states',en:'Use Storybook as the review surface for product components before page integration. AI writes code; humans define states.'},
      outcomes:{th:['เข้าใจ Story = ตัวอย่าง state ที่ทำซ้ำได้','สั่ง Agent สร้าง Component.tsx + Component.stories.tsx คู่กัน','review UI ผ่าน browser โดยไม่ต้องอ่านโค้ดทุกบรรทัด','ใช้ mock data ที่ deterministic ใน stories'],en:['Understand a Story as a repeatable UI state','Ask the agent to create Component.tsx + Component.stories.tsx together','Review UI in the browser without reading every line of code','Use deterministic mock data in stories']},
      blocks:[
        {type:'diagram',title:{th:'Component-driven loop',en:'Component-driven loop'},diagram:`flowchart LR\nAC[Acceptance Criteria] --> ST[UI States]\nST --> S[Storybook Stories]\nS --> C[Component]\nC --> H[Human Visual Review]\nH -->|feedback| C\nH -->|approved| P[Integrate into Page]`},
        {type:'code',label:'Agent prompt',code:`Implement PatientSearch as an isolated product component.\n\nCreate these files together:\n- PatientSearch.tsx\n- PatientSearch.stories.tsx\n\nRequired stories:\n- Default\n- Loading\n- Empty\n- WithResults\n- Error\n\nUse deterministic mock/synthetic patient data.\nDo not connect to a real backend.\nDo not integrate into the page yet.\nDo not commit or push.`},
        {type:'list',title:{th:'Human review ใน Storybook ดูอะไร',en:'What humans review in Storybook'},items:{th:['คำและข้อความสอดคล้อง Requirement','Visual hierarchy อ่านง่าย','Loading/Empty/Error ไม่ทำให้ผู้ใช้สับสน','ข้อมูลยาว/optional field ไม่ทำ layout พัง','Interaction controls มีความหมาย'],en:['Copy matches the requirement','Visual hierarchy is easy to scan','Loading/Empty/Error are understandable','Long/optional data does not break layout','Interaction controls are meaningful']}},
        {type:'practice',title:{th:'ลงมือทำ: PatientSearch stories',en:'Practice: PatientSearch stories'},steps:{th:['ส่ง prompt ให้ Agent','รัน Storybook','เปิด story ทั้ง 5 state ทีละตัว','จด feedback ในภาษาของ Product ไม่ต้องอธิบายวิธีเขียน code','ให้ Agent ปรับแล้ว review ซ้ำ'],en:['Send the prompt to the agent','Run Storybook','Open all five states one by one','Write product-language feedback without prescribing code','Ask the agent to revise and review again']},expected:{th:'มี PatientSearch component กับ stories 5 state ที่เปิดได้แยกกัน และยังไม่ผูกกับ page จริง',en:'A PatientSearch component with five independently viewable stories, not yet integrated into the real page.'}}
      ],
      quiz:{q:{th:'ใครควรเป็นเจ้าของการนิยาม “ต้องมี Story อะไรบ้าง”?',en:'Who should own the decision about which stories matter?'},options:{th:['AI อย่างเดียว','Human จาก requirement/state แล้วให้ AI implement','Storybook CLI'],en:['AI alone','Humans derive them from requirements/states, then AI implements','Storybook CLI']},answer:1,why:{th:'AI ช่วยเสนอได้ แต่ state ที่ต้องครอบคลุมเป็น product decision',en:'AI can suggest, but required state coverage is a product decision.'}},
      wrap:{th:['Storybook คือพื้นที่ review ไม่ใช่แค่เอกสารของ Dev','Component และ Story เดินคู่กัน','Human ระบุ state; AI รับผิดชอบ implementation'],en:['Storybook is a review surface, not just dev documentation','Components and stories move together','Humans define states; AI handles implementation']}
    },
    {
      id:'acceptance-interaction', group:'day2', no:'08', duration:'60 min',
      title:{th:'Storybook as Acceptance Example & Interaction',en:'Storybook as Acceptance Example & Interaction'},
      intro:{th:'เชื่อม Acceptance Criteria กับ Story และ interaction scenario เพื่อให้ BA/PM อ่านแล้วเห็น behavior ที่คาดหวัง',en:'Connect acceptance criteria to stories and interaction scenarios so PM/BA can see expected behavior directly.'},
      outcomes:{th:['map AC → Story ได้','เขียน Given/When/Then ในภาษาธุรกิจ','ให้ AI แปลง scenario เป็น Storybook interaction test','แยก visual state กับ behavior flow'],en:['Map AC → Story','Write Given/When/Then in business language','Let AI translate scenarios into Storybook interaction tests','Separate visual states from behavioral flows']},
      blocks:[
        {type:'two',title:{th:'Acceptance → Story',en:'Acceptance → Story'},left:{title:{th:'Requirement',en:'Requirement'},items:{th:['AC: ไม่พบผู้ป่วย','AC: ระบบค้นหาขัดข้อง','AC: พบผู้ป่วยหลายคน'],en:['AC: No patient found','AC: Search service fails','AC: Multiple patients found']}},right:{title:{th:'Story',en:'Story'},items:{th:['Empty','Error','WithResults'],en:['Empty','Error','WithResults']}}},
        {type:'code',label:'BDD-style scenario',code:`Given Patient Search is displayed\nWhen the user enters HN "65000123"\nAnd clicks Search\nThen a patient named "Somchai Jaidee" is displayed`},
        {type:'code',label:'Agent prompt',code:`Add a Storybook interaction scenario for PatientSearch.\n\nBusiness scenario:\nGiven Patient Search is displayed\nWhen the user enters HN "65000123"\nAnd clicks Search\nThen patient "Somchai Jaidee" is displayed.\n\nUse the existing mock service and deterministic data.\nKeep the test readable and aligned with the acceptance criteria.`},
        {type:'practice',title:{th:'ลงมือทำ: AC coverage matrix',en:'Practice: AC coverage matrix'},steps:{th:['เปิด requirement US-001','จับคู่ AC ที่เป็น visual state กับ story','เลือก 1 behavior flow แล้วเขียน Given/When/Then','ให้ Agent implement interaction','รันและดู interaction step-by-step ใน Storybook'],en:['Open requirement US-001','Map visual acceptance criteria to stories','Choose one behavior flow and write Given/When/Then','Ask the agent to implement the interaction','Run and inspect the interaction step-by-step in Storybook']},expected:{th:'มีหลักฐานชัดว่า AC สำคัญถูก represent ด้วย story หรือ interaction และผู้เรียนอธิบาย coverage ได้',en:'There is clear evidence that key ACs are represented by stories or interactions, and you can explain the coverage.'}}
      ],
      quiz:{q:{th:'Given/When/Then มีประโยชน์หลักกับกลุ่มนี้เพราะอะไร?',en:'Why is Given/When/Then especially useful for this audience?'},options:{th:['ทำให้ไม่ต้องมี requirement','เป็นภาษากลางระหว่าง business behavior กับ test implementation','ทำให้ Git เร็วขึ้น'],en:['It eliminates requirements','It is a shared language between business behavior and test implementation','It makes Git faster']},answer:1,why:{th:'BA/PM สามารถนิยาม behavior โดยไม่ต้องรู้ test syntax แล้วให้ Agent แปลงเป็น implementation',en:'PM/BA can define behavior without test syntax, then let the agent implement it.'}},
      wrap:{th:['Story = state example','Interaction = behavior example','Acceptance Criteria สามารถ trace ไปยังสิ่งที่เปิดดู/รันได้'],en:['Story = state example','Interaction = behavior example','Acceptance criteria can trace to something visible/runnable']}
    },
    {
      id:'mock-data', group:'day3', no:'09', duration:'45 min',
      title:{th:'Mock Data / Mock API โดยไม่ต้องเรียน Backend',en:'Mock Data / Mock API Without Learning Backend'},
      intro:{th:'จำลอง response ที่ UI ต้องรับมือให้ครบ โดยไม่เสียเวลาเรียน server, database หรือ authentication',en:'Simulate the responses the UI must handle without spending course time on servers, databases, or authentication.'},
      outcomes:{th:['เข้าใจ request/response แค่ระดับ concept','สร้าง scenario success/empty/slow/error ด้วย mock','ใช้ synthetic HIS data อย่างปลอดภัย','รู้ว่า mock contract ควร stable และ deterministic'],en:['Understand request/response at concept level','Model success/empty/slow/error using mocks','Use safe synthetic HIS data','Keep mock contracts stable and deterministic']},
      blocks:[
        {type:'diagram',title:{th:'Training architecture',en:'Training architecture'},diagram:`flowchart LR\nUI[Next.js UI] --> S[Mock Service]\nS --> D[(Synthetic Data)]\nS --> N[normal]\nS --> L[slow]\nS --> E[empty]\nS --> X[error]`},
        {type:'callout',title:{th:'ในระบบจริงมี Backend แต่คอร์สนี้ไม่จำเป็นต้องรู้ implementation',en:'A real system has a backend, but this course does not need its implementation'},text:{th:'สิ่งที่ Product role ต้องคิดคือ UI ทำอะไรเมื่อ response ช้า, ว่าง, ผิดพลาด หรือสำเร็จ ไม่ใช่ว่า database query เขียนอย่างไร',en:'The product role needs to decide what UI does when responses are slow, empty, erroneous, or successful — not how database queries are written.'}},
        {type:'code',label:'Synthetic examples',code:`65000123 -> Somchai Jaidee\n65000124 -> Somying Sukjai\n99999999 -> []          # empty\nERROR      -> throw Error # error\nSLOW       -> 2000ms delay`},
        {type:'practice',title:{th:'ลงมือทำ: บังคับทุก state ด้วย mock',en:'Practice: force every state with mocks'},steps:{th:['ใช้ mock scenario normal แล้วค้นหา HN ที่มีข้อมูล','ใช้ empty แล้วตรวจ Empty state','ใช้ slow แล้วตรวจ Loading state','ใช้ error แล้วตรวจ Error state'],en:['Use normal and search a known HN','Use empty and inspect Empty state','Use slow and inspect Loading state','Use error and inspect Error state']},expected:{th:'เปิด UI state ทั้ง 4 แบบได้ซ้ำ ๆ โดยไม่ต้องมี Backend จริงและไม่ใช้ข้อมูลผู้ป่วยจริง',en:'You can repeatedly reproduce all four UI states without a real backend or real patient data.'}}
      ],
      quiz:{q:{th:'คุณสมบัติที่สำคัญของ mock สำหรับ training คืออะไร?',en:'What is important for training mocks?'},options:{th:['สุ่มทุกครั้งเพื่อสมจริง','Deterministic และใช้ synthetic data','ต่อ production เพื่อข้อมูลใหม่เสมอ'],en:['Random every time for realism','Deterministic and synthetic','Always connect to production for fresh data']},answer:1,why:{th:'ผลที่ทำซ้ำได้ช่วยให้เรียน, review และ debug ได้ง่ายและปลอดภัย',en:'Repeatable outcomes make learning, review, and debugging easier and safer.'}},
      wrap:{th:['ตัด Backend ได้โดยไม่เสียเป้าหมายหลัก','Mock ใช้สร้าง state ที่ต้อง review','Training HIS ต้องใช้ synthetic data'],en:['Backend can be removed without losing the course goal','Mocks create reviewable states','HIS training must use synthetic data']}
    },
    {
      id:'integration', group:'day3', no:'10', duration:'60 min',
      title:{th:'Assemble Components into OPD Check-in Page',en:'Assemble Components into the OPD Check-in Page'},
      intro:{th:'เมื่อ component ผ่าน Storybook review แล้ว ค่อยให้ Agent ประกอบเป็น flow จริงบน Next.js page',en:'After components pass Storybook review, let the agent assemble them into the real Next.js flow.'},
      outcomes:{th:['เห็นความต่างระหว่าง isolated component กับ integrated flow','review state transition ทั้งหน้า','ตรวจ validation และ confirmation flow','ใช้ mock service เดิมโดยไม่สร้าง backend'],en:['See the difference between isolated components and an integrated flow','Review state transitions across the page','Check validation and confirmation flow','Reuse the mock service without adding a backend']},
      blocks:[
        {type:'diagram',title:{th:'OPD Check-in flow',en:'OPD Check-in flow'},diagram:`flowchart TD\nA[Search HN / Name] --> B{Result}\nB -->|loading| L[Loading]\nB -->|empty| E[Empty]\nB -->|error| X[Error]\nB -->|found| R[Select Patient]\nR --> F[Choose Clinic + Chief Complaint]\nF --> V{Valid?}\nV -->|No| VE[Validation message]\nV -->|Yes| P[Preview]\nP --> C[Confirm]\nC --> S[Check-in Success + Queue No.]`},
        {type:'code',label:'Integration prompt',code:`Integrate the reviewed OPD check-in components into /opd/check-in.\n\nRequirements:\n- Reuse existing components and mock service.\n- Preserve all reviewed Storybook states.\n- Clinic is required.\n- Chief Complaint is optional.\n- Show a preview/confirmation before final submit.\n- Final success displays a synthetic queue number.\n- Do not add a backend or database.\n- Keep the change scoped to US-001.\n\nAfter implementation, run the app and summarize the state transitions.`},
        {type:'practice',title:{th:'ลงมือทำ: Walk the flow',en:'Practice: walk the flow'},steps:{th:['ให้ Agent integrate ตาม prompt','เปิด /opd/check-in','เดิน flow ปกติจน Success','ย้อนกลับทดสอบ Validation, Empty และ Error','จดปัญหาเป็น behavior feedback ไม่ใช่ code instruction'],en:['Ask the agent to integrate with the prompt','Open /opd/check-in','Walk the happy path to Success','Repeat for Validation, Empty, and Error','Write issues as behavior feedback, not code instructions']},expected:{th:'Flow หลักทำงานครบจาก Search → Select → Form → Preview → Confirm → Success และ state สำคัญยังทดสอบได้',en:'The main flow works from Search → Select → Form → Preview → Confirm → Success, with key states still testable.'}}
      ],
      quiz:{q:{th:'ทำไมควร review component ใน Storybook ก่อน integrate?',en:'Why review components in Storybook before integration?'},options:{th:['เพื่อให้ไฟล์เยอะขึ้น','แยกปัญหา component/state ออกจากปัญหา page integration','เพราะ Next.js เปิด Storybook ไม่ได้'],en:['To create more files','To separate component/state problems from page-integration problems','Because Next.js cannot open Storybook']},answer:1,why:{th:'การแยก review layer ลดความซับซ้อนเมื่อเกิดปัญหา',en:'Separating review layers reduces complexity when something goes wrong.'}},
      wrap:{th:['Review isolated ก่อน integrated','ตรวจ state transition ไม่ใช่แค่ screenshot','ยังใช้ mock ได้ครบโดยไม่มี backend'],en:['Review isolated before integrated','Review state transitions, not just screenshots','Mocks remain sufficient without a backend']}
    },
    {
      id:'debugging', group:'day3', no:'11', duration:'75 min',
      title:{th:'Debugging Literacy สำหรับผู้ใช้ AI Agent',en:'Debugging Literacy for AI-Agent Users'},
      intro:{th:'ไม่ต้องแก้ error เองทุกครั้ง แต่ต้องหา evidence, ระบุตำแหน่งปัญหา และให้ Agent อธิบาย root cause ก่อนแก้',en:'You do not have to fix every error yourself, but you must gather evidence, locate the problem, and ask the agent to explain root cause before fixing it.'},
      outcomes:{th:['รู้ 4 แหล่งหลัก: Terminal, Browser UI, Console, Network','อ่าน Error type → message → file → line','แยก UI symptom กับ data/service failure','หยุดวงจร “fix ซ้ำโดยไม่เข้าใจ”'],en:['Know the four evidence sources: Terminal, Browser UI, Console, Network','Read Error type → message → file → line','Separate UI symptoms from data/service failures','Stop the “blind repeated fix” loop']},
      blocks:[
        {type:'diagram',title:{th:'Debug loop',en:'Debug loop'},diagram:`flowchart LR\nE[Observe error] --> C[Collect evidence]\nC --> U[Understand root cause]\nU --> H[Hypothesis]\nH --> F[Small fix]\nF --> V[Verify]\nV -->|still fails| E\nV -->|passes| D[Review diff]`},
        {type:'list',title:{th:'4 จุดที่ต้องเปิดเป็น',en:'Four places you should know'},items:{th:['Terminal: build/runtime/type error','Browser UI: สิ่งที่ผู้ใช้เห็นจริง','Console: JavaScript/runtime warnings/errors','Network: request status, response และ timing'],en:['Terminal: build/runtime/type errors','Browser UI: what the user actually sees','Console: JavaScript/runtime warnings/errors','Network: request status, response, and timing']}},
        {type:'code',label:'Root-cause prompt',code:`Explain this error before changing anything.\n\nTell me:\n1. What failed?\n2. What evidence supports that?\n3. What is the root cause?\n4. Which file(s) are involved?\n5. What is the smallest safe fix?\n6. How will we verify the fix?\n\nDo not modify files yet.`},
        {type:'two',title:{th:'Intentional errors ใน workshop',en:'Intentional workshop errors'},left:{title:{th:'ตัวอย่าง',en:'Examples'},items:{th:['TypeScript property error','Mock error scenario','Port 3000 in use','Missing UI state'],en:['TypeScript property error','Mock error scenario','Port 3000 in use','Missing UI state']}},right:{title:{th:'สิ่งที่ฝึก',en:'What it trains'},items:{th:['อ่าน terminal','แยก expected error state จาก bug','เข้าใจหลาย worktree/process','ย้อนกลับไป requirement/state inventory'],en:['Read terminal evidence','Separate expected error state from bugs','Understand multiple worktrees/processes','Return to requirement/state inventory']}}},
        {type:'practice',title:{th:'ลงมือทำ: Diagnose ก่อน Fix',en:'Practice: diagnose before fixing'},steps:{th:['เลือก intentional error จาก docs/workshop-errors.md','เก็บ error text และตำแหน่ง','ส่ง Root-cause Prompt ให้ Agent','อธิบาย root cause ด้วยคำของตัวเองก่อนอนุญาตให้ Agent แก้','หลังแก้ให้ reproduce case เดิมเพื่อยืนยัน'],en:['Choose an intentional error from docs/workshop-errors.md','Capture the error text and location','Send the Root-cause Prompt','Explain root cause in your own words before allowing a fix','Reproduce the original case after the fix']},expected:{th:'สามารถบอกได้ว่าอะไรเสีย, หลักฐานอยู่ที่ไหน, root cause คืออะไร และ fix ถูก verify อย่างไร',en:'You can state what failed, where the evidence is, the root cause, and how the fix was verified.'}}
      ],
      quiz:{q:{th:'เมื่อ Agent แก้ error แล้วเกิด error ใหม่ สิ่งที่ควรทำที่สุดคือ?',en:'When an agent fixes one error and creates another, what should you do?'},options:{th:['พิมพ์ “fix” ซ้ำไปเรื่อยๆ','กลับไปเก็บ evidence และเข้าใจ root cause ก่อนแก้อีกครั้ง','ลบ tests'],en:['Keep typing “fix”','Collect evidence again and understand root cause before another change','Delete the tests']},answer:1,why:{th:'Debugging ที่ดีเป็น loop ที่มี evidence และ verification ไม่ใช่การสุ่มเปลี่ยน code',en:'Good debugging is an evidence-and-verification loop, not random code changes.'}},
      wrap:{th:['อ่าน evidence ก่อนถาม AI','ขอ root cause ก่อน fix','verify ด้วย case ที่เคยพัง'],en:['Read evidence before asking AI','Ask for root cause before a fix','Verify using the case that previously failed']}
    },
    {
      id:'diff-quality', group:'day3', no:'12', duration:'60 min',
      title:{th:'Git Diff, Scope Review & Quality Gates',en:'Git Diff, Scope Review & Quality Gates'},
      intro:{th:'ก่อนเชื่อว่า Agent ทำงานเสร็จ ตรวจสิ่งที่เปลี่ยนจริงและให้เครื่องมือพื้นฐานช่วยจับปัญหา',en:'Before trusting that the agent is finished, inspect the actual changes and run basic quality gates.'},
      outcomes:{th:['ใช้ status/diff เพื่อจับ scope creep','ให้ Agent อธิบาย changed files ทีละไฟล์','รัน lint/test/build','รู้สัญญาณ red flag แม้อ่าน code ไม่ลึก'],en:['Use status/diff to catch scope creep','Ask the agent to explain changed files one by one','Run lint/test/build','Recognize red flags without deep code-reading']},
      blocks:[
        {type:'code',label:'Review commands',code:`git status\ngit diff --stat\ngit diff\n\nnpm run lint\nnpm run test\nnpm run build`},
        {type:'callout',tone:'danger',title:{th:'Red flag',en:'Red flag'},text:{th:'Issue ขอแก้ Patient Search แต่ git diff แสดง 21 files รวม auth, package.json และ global layout — อย่า commit ก่อนเข้าใจว่าทำไมทุกไฟล์จำเป็น',en:'The issue asks for Patient Search, but git diff shows 21 files including auth, package.json, and global layout — do not commit until you understand why every file is necessary.'}},
        {type:'code',label:'Diff review prompt',code:`Review the current git diff.\n\n1. Summarize the change in product terms.\n2. Explain every changed file and why it is necessary for US-001.\n3. Identify unrelated or accidental changes.\n4. Identify risky changes or new dependencies.\n5. Confirm what was verified.\n\nDo not modify anything.`},
        {type:'practice',title:{th:'ลงมือทำ: Scope audit',en:'Practice: scope audit'},steps:{th:['รัน git status และ git diff --stat','คาดการณ์ก่อนว่าควรมีไฟล์ประเภทไหนเปลี่ยน','ให้ Agent review diff ด้วย prompt','เปิด diff ของไฟล์ที่น่าสงสัย','รัน lint/test/build และบันทึกผล'],en:['Run git status and git diff --stat','Predict what kinds of files should have changed','Ask the agent to review the diff','Open suspicious file diffs','Run lint/test/build and record results']},expected:{th:'สามารถอธิบาย changed-file set ได้ ไม่มีไฟล์นอก scope ที่อธิบายไม่ได้ และ quality checks ผ่าน',en:'You can explain the changed-file set, no unexplained out-of-scope files remain, and quality checks pass.'}}
      ],
      quiz:{q:{th:'“npm run build ผ่าน” แปลว่างานเสร็จหรือไม่?',en:'Does “npm run build passes” mean the work is complete?'},options:{th:['เสร็จแน่นอน','ไม่เสมอ ต้องตรวจ requirement, UI states, interaction และ diff ด้วย','เสร็จถ้า AI บอกว่าเสร็จ'],en:['Definitely','Not necessarily; requirements, UI states, interaction, and diff still need review','Yes if the AI says so']},answer:1,why:{th:'Build ตรวจความสามารถในการ build ไม่ได้ยืนยันว่าพฤติกรรมและ scope ถูกต้อง',en:'A build checks buildability, not product behavior or scope correctness.'}},
      wrap:{th:['Diff เป็นเครื่องมือตรวจ AI ที่สำคัญที่สุดตัวหนึ่ง','Quality gate หลายชั้นดีกว่า “AI said done”','Scope ต้องอธิบายได้ทุกไฟล์'],en:['Diff is one of the most important AI-review tools','Layered quality gates beat “AI said done”','Every changed file should be explainable']}
    },
    {
      id:'delivery', group:'day3', no:'13', duration:'30 min',
      title:{th:'Commit, Push & Merge Request',en:'Commit, Push & Merge Request'},
      intro:{th:'ส่งงานให้ Developer review ด้วย MR ที่บอก intent, scope, states และ evidence ชัดเจน',en:'Deliver work for developer review with an MR that clearly communicates intent, scope, states, and evidence.'},
      outcomes:{th:['commit งานที่ผ่าน review แล้ว','push feature branch โดยไม่แตะ main','เขียน MR ที่ review ง่าย','ย้าย workflow จาก GitHub starter ไป GitLab self-hosted ได้'],en:['Commit reviewed work','Push a feature branch without touching main','Write an easy-to-review MR','Move the starter workflow from GitHub to self-hosted GitLab']},
      blocks:[
        {type:'code',label:'Delivery',code:`git status\ngit diff\ngit add .\ngit commit -m "feat: add OPD patient check-in"\ngit push -u origin feature/us001-patient-checkin`},
        {type:'code',label:'MR template',code:`## What\nImplement OPD Patient Check-in (US-001).\n\n## Implemented\n- Patient search and selection\n- Loading / Empty / Error states\n- Clinic validation\n- Preview / Confirm / Success\n\n## Verification\n- Storybook reviewed\n- Interaction checks pass\n- npm run lint\n- npm run test\n- npm run build\n- git diff reviewed\n\n## Data\nSynthetic/mock data only. No production data.`},
        {type:'callout',title:{th:'ใช้กับ GitLab self-hosted ได้เหมือนกัน',en:'The same workflow works with self-hosted GitLab'},text:{th:'Starter อยู่ GitHub เพื่อให้ Fork/Download ง่าย แต่ผู้เรียนสามารถสร้าง project ใน GitLab บริษัท แล้วเปลี่ยน remote และ Push feature branch เข้า GitLab ได้',en:'The starter lives on GitHub for easy fork/download, but learners can create a project in the company GitLab, change the remote, and push the feature branch there.'}},
        {type:'code',label:'Move remote to GitLab',code:`git remote -v\ngit remote set-url origin git@gitlab.company.local:training/your-project.git\ngit push -u origin feature/us001-patient-checkin`},
        {type:'practice',title:{th:'ลงมือทำ: Draft MR',en:'Practice: draft an MR'},steps:{th:['commit หลัง checks ผ่าน','push branch','สร้าง Draft MR','ใช้ template สรุป requirement, states และ verification','ให้เพื่อนอีกคนอ่าน MR แล้วตอบว่าเข้าใจ scope หรือไม่'],en:['Commit after checks pass','Push the branch','Create a Draft MR','Use the template to summarize requirements, states, and verification','Ask a peer whether the MR makes the scope clear']},expected:{th:'มี Draft MR ที่ Developer สามารถเริ่ม review ได้โดยไม่ต้องถามว่า “ทำอะไรมา?”',en:'A Draft MR that a developer can start reviewing without first asking “What did you change?”'}}
      ],
      quiz:{q:{th:'MR ที่ดีควรเน้นอะไร?',en:'What should a good MR emphasize?'},options:{th:['จำนวนบรรทัดที่ AI เขียน','Intent + scope + verification evidence','ชื่อ model ที่ใช้'],en:['Lines of code produced by AI','Intent + scope + verification evidence','The model name used']},answer:1,why:{th:'Reviewer ต้องเข้าใจว่าทำไมเปลี่ยน, เปลี่ยนอะไร และตรวจแล้วอย่างไร',en:'Reviewers need to know why it changed, what changed, and how it was verified.'}},
      wrap:{th:['Feature branch → MR → Developer review','MR คือ handoff artifact','GitHub starter สามารถย้ายไป GitLab workflow ได้'],en:['Feature branch → MR → Developer review','The MR is the handoff artifact','The GitHub starter can move into a GitLab workflow']}
    },
    {
      id:'capstone', group:'capstone', no:'14', duration:'90 min', kind:'capstone',
      title:{th:'Capstone · OPD Patient Check-in Lite',en:'Capstone · OPD Patient Check-in Lite'},
      intro:{th:'ทำ flow เดิมให้ครบด้วยตัวเองตั้งแต่ Issue จนถึง Draft MR โดยมี Guided Mode แบบเปิดทีละขั้นเมื่อจำเป็น — ไม่โชว์เฉลยทั้งหมดตั้งแต่แรก',en:'Complete the same flow independently from Issue to Draft MR, with a progressive Guided Mode you reveal only when needed — not a full solution upfront.'},
      outcomes:{th:['รวมทุกทักษะในสถานการณ์ HIS เดียว','รู้ว่าเมื่อไรควรขอ hint และเมื่อไรควรให้ Agent ทำต่อ','สร้าง reviewable evidence ครบทั้ง Storybook, app, checks และ diff','ประเมินความพร้อมก่อนเข้า course หลัก'],en:['Combine all skills in one HIS scenario','Know when to use a hint and when to let the agent continue','Produce reviewable evidence across Storybook, app, checks, and diff','Assess readiness for the main course']},
      blocks:[
        {type:'callout',title:{th:'ทำไม Capstone มี Guideline',en:'Why the Capstone includes a guideline'},text:{th:'มีได้และควรมีสำหรับกลุ่มผู้เริ่มต้น แต่ใช้แบบ Progressive Disclosure: ลองเองก่อน → เปิด Hint → เปิด Step-by-step เฉพาะเมื่อค้าง เพื่อไม่ให้กลายเป็นการ copy solution',en:'It should exist for beginners, but use progressive disclosure: try first → reveal a hint → reveal step-by-step only when stuck, so it does not become solution copying.'}},
        {type:'diagram',title:{th:'Target flow',en:'Target flow'},diagram:`flowchart TD\nS[Search patient] --> R{Response}\nR -->|loading| L[Loading]\nR -->|empty| E[Empty]\nR -->|error| X[Error]\nR -->|results| P[Select patient]\nP --> F[Clinic + Chief Complaint]\nF --> V{Clinic selected?}\nV -->|No| M[Validation]\nV -->|Yes| C[Preview & Confirm]\nC --> O[Success + Queue A012]`},
        {type:'list',title:{th:'Definition of Done',en:'Definition of Done'},items:{th:['Search ด้วย HN หรือชื่อ','Loading / Empty / Error / WithResults','เลือกผู้ป่วยและแสดงข้อมูล','Clinic required; Chief Complaint optional','Preview/Confirm ก่อน final action','Success พร้อม synthetic queue number','Meaningful Storybook stories','อย่างน้อย 1 interaction scenario','lint/test/build ผ่าน','git diff reviewed และ Draft MR พร้อม'],en:['Search by HN or name','Loading / Empty / Error / WithResults','Select and display a patient','Clinic required; Chief Complaint optional','Preview/Confirm before final action','Success with a synthetic queue number','Meaningful Storybook stories','At least one interaction scenario','lint/test/build pass','git diff reviewed and Draft MR ready']}},
        {type:'capstone',steps:[
          {title:{th:'1 · ตั้ง Workspace',en:'1 · Set up the workspace'},hint:{th:'เริ่มจาก main ที่ clean แล้วใช้ worktree แยก task',en:'Start from clean main and isolate the task with a worktree'},guide:{th:'รัน git status → git pull → git worktree add ... -b feature/us001-patient-checkin main → cd เข้า worktree → git status',en:'Run git status → git pull → git worktree add ... -b feature/us001-patient-checkin main → cd into the worktree → git status'}},
          {title:{th:'2 · Explore & Plan',en:'2 · Explore & Plan'},hint:{th:'ยังไม่ให้ Agent แก้ไฟล์ ให้มันอ่าน AGENTS.md + requirement และรายงาน component/state/file scope',en:'Do not allow edits yet. Ask it to read AGENTS.md + the requirement and report component/state/file scope'},guide:{th:'ใช้ Explore Prompt จากบท 04 แล้ว review ว่าครบ Loading/Empty/Error/Validation/Success และ file scope แคบพอ',en:'Use the Explore Prompt from lesson 04, then review Loading/Empty/Error/Validation/Success coverage and file scope'}},
          {title:{th:'3 · Component + State Map',en:'3 · Component + State Map'},hint:{th:'อย่าเริ่มจากหน้าใหญ่ก้อนเดียว',en:'Do not start with one giant page component'},guide:{th:'เริ่ม PatientSearch → PatientResults → SelectedPatient → CheckInForm → Confirmation → Success แล้วกำหนด meaningful states เฉพาะที่แต่ละ component ต้องรับผิดชอบ',en:'Start with PatientSearch → PatientResults → SelectedPatient → CheckInForm → Confirmation → Success, then define only meaningful states each owns'}},
          {title:{th:'4 · Storybook First',en:'4 · Storybook First'},hint:{th:'สร้าง component + story คู่กัน และใช้ mock deterministic',en:'Create component + story pairs with deterministic mocks'},guide:{th:'ให้ Agent ทำ PatientSearch ก่อน พร้อม Default/Loading/Empty/WithResults/Error; review แล้วจึงทำ component ถัดไป',en:'Have the agent build PatientSearch first with Default/Loading/Empty/WithResults/Error; review it before moving on'}},
          {title:{th:'5 · Interaction',en:'5 · Interaction'},hint:{th:'เลือก behavior สำคัญ 1 flow เขียน Given/When/Then',en:'Choose one important behavior and write Given/When/Then'},guide:{th:'เช่น HN 65000123 → click Search → Somchai Jaidee แสดง แล้วให้ Agent ทำ Storybook interaction',en:'For example HN 65000123 → click Search → Somchai Jaidee appears, then ask the agent to add the Storybook interaction'}},
          {title:{th:'6 · Integrate Page',en:'6 · Integrate the page'},hint:{th:'ประกอบเฉพาะ component ที่ review แล้ว และ reuse mock service',en:'Assemble only reviewed components and reuse the mock service'},guide:{th:'ให้ Agent integrate เข้า /opd/check-in แล้ว walkthrough happy path + validation + empty + error',en:'Ask the agent to integrate into /opd/check-in, then walk the happy path + validation + empty + error'}},
          {title:{th:'7 · Diagnose Intentional Error',en:'7 · Diagnose an intentional error'},hint:{th:'อ่าน error ก่อน fix และขอ root cause',en:'Read the error before fixing and ask for root cause'},guide:{th:'เลือก error จาก docs/workshop-errors.md, capture evidence, ใช้ Root-cause Prompt, อธิบายเหตุผลด้วยคำตัวเอง แล้วค่อยแก้',en:'Choose an error from docs/workshop-errors.md, capture evidence, use the Root-cause Prompt, explain it yourself, then fix'}},
          {title:{th:'8 · Diff & Quality Gates',en:'8 · Diff & Quality Gates'},hint:{th:'คาดการณ์ changed files ก่อนดูจริง',en:'Predict the changed files before reviewing them'},guide:{th:'git status → git diff --stat → git diff → Agent diff review → npm run lint/test/build',en:'git status → git diff --stat → git diff → agent diff review → npm run lint/test/build'}},
          {title:{th:'9 · Draft MR',en:'9 · Draft MR'},hint:{th:'MR ต้องเล่า intent, scope, states และ evidence',en:'The MR should tell intent, scope, states, and evidence'},guide:{th:'Commit → push feature branch → Draft MR ตาม template → ให้ peer review ความชัดเจนก่อนส่ง Developer',en:'Commit → push feature branch → Draft MR using the template → ask a peer to review clarity before developer handoff'}}
        ]},
        {type:'practice',title:{th:'ผลลัพธ์ที่คาดหวังจาก Capstone',en:'Expected Capstone result'},steps:{th:['Storybook แสดง meaningful states ของ OPD Check-in','/opd/check-in เดิน flow ได้ด้วย mock data','ผู้เรียนอธิบาย error หนึ่งกรณีและวิธี verify fix ได้','Diff อยู่ใน scope และ quality checks ผ่าน','Draft MR พร้อม evidence สำหรับ Developer review'],en:['Storybook shows meaningful OPD Check-in states','/opd/check-in runs end-to-end on mock data','You can explain one error and how the fix was verified','Diff stays in scope and quality checks pass','Draft MR contains evidence for developer review']},expected:{th:'ไม่ต้องได้ “โค้ดที่สมบูรณ์แบบ” เป้าหมายคือ workflow ที่ควบคุมได้ ตรวจสอบได้ และ handoff ได้',en:'The goal is not “perfect code”; it is a controllable, verifiable workflow that can be handed off.'}}
      ],
      quiz:{q:{th:'ตัวชี้วัดความสำเร็จของ Capstone ที่สำคัญที่สุดคืออะไร?',en:'What is the most important Capstone success signal?'},options:{th:['จำนวนโค้ดที่ Agent สร้าง','สามารถอธิบายและตรวจทุกขั้นจาก requirement ถึง MR ได้','UI มี animation เยอะที่สุด'],en:['Amount of generated code','You can explain and verify every step from requirement to MR','The UI has the most animations']},answer:1,why:{th:'หลักสูตรนี้วัดความสามารถในการกำกับ AI-assisted development ไม่ใช่ความเร็วในการสร้าง code',en:'This course measures the ability to supervise AI-assisted development, not raw code-generation speed.'}},
      wrap:{th:['ทำ end-to-end workflow ได้ด้วยโจทย์ HIS เดียว','ใช้ hints แบบช่วยคิด ไม่ใช่ copy solution','พร้อมเข้าสู่การเรียนกับอาจารย์โดยมี common workflow เดียวกัน'],en:['Complete an end-to-end workflow on one HIS scenario','Use hints to unblock thinking rather than copy a solution','Enter the main class with a shared working workflow']}
    }
  ],
  final: {
    title:{th:'สิ่งที่คุณทำได้หลังจบเส้นทางนี้',en:'What you can do after this journey'},
    intro:{th:'คุณไม่จำเป็นต้องเรียกตัวเองว่า Developer แต่ควรสามารถรับ Requirement หนึ่งเรื่องและกำกับ AI Agent จนกลายเป็นงาน Frontend ที่ตรวจสอบและส่งต่อได้',en:'You do not need to call yourself a developer. You should be able to take one requirement and supervise an AI agent until it becomes verifiable frontend work ready for handoff.'},
    skills:{th:['Requirement → Component/State','Git branch + worktree','Agent Explore/Plan','Storybook review','Mock states','Browser/Terminal debugging','git diff + quality gates','Commit/Push/MR'],en:['Requirement → Component/State','Git branch + worktree','Agent Explore/Plan','Storybook review','Mock states','Browser/Terminal debugging','git diff + quality gates','Commit/Push/MR']}
  }
};
